---
- name: Configure CSR1000v router
  hosts: CSR1kv
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
  tasks:
    - name: Configure Loopback interface
      ios_config:
        lines:
          - interface Loopback12
          - description Loopback interface for testing
          - ip address 12.1.2.3 255.255.255.0


      
      
